[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://crypto-crash-game-h8w6.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
